### ISSUE TITLE
Setup Readthedocs.org 

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress-docs-rtd#1]
Need to setup the repo to work with Readthedocs.org and get the subdomain docs.classicpress.net

**Comment by Tmeister** [comment]
Correct me but I think the issue is no longer valid right, according to the Slack channel, Readthedocs won't happen.

I'm just checking this TODO list just want to know what in there is going to happen.

**Comment by nylen** [comment]
Yep, I think so. Since no one has done anything on this yet, I pointed docs.classicpress.net to a ClassicPress site:

- Simple to get up and running
- We own the content
- We can integrate this repository into the site later, one approach to follow is https://github.com/wp-cli/handbook
