### ISSUE TITLE
Creating documentation: Intial topics

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress-docs-rtd#3]
We need to decide the high priority documentation that will be put together. Please add your suggestions below.

**Comment by bahiirwa** [comment]
Migrating old WP themes or plugins to ClassicPress "friendly" versions

**Comment by nylen** [comment]
> Migrating old WP themes or plugins to ClassicPress "friendly" versions

Step 1: do nothing.

End of steps.

That is the ideal, at least.  If that doesn't work for ClassicPress v1, then we did something wrong.

**Comment by nylen** [comment]
This has been done for a while, docs.classicpress.net is up with basic documentation.
